version: '3.1'
services:
  postgres:
    image: postgres:9.6-alpine
    command: postgres -c log_statement=all
    restart: always
    environment:
      POSTGRES_USER: codelab
      POSTGRES_PASSWORD: codelab
      POSTGRES_DB: codelab
    ports:
      - 5432:5432
